"""ReAct (Reason + Act) Agent Scaffolding Harness for OpenEval Studio.

Orchestrates multi-turn thought-action-observation cycles for benchmark task resolution,
token tracking, and structured trajectory capture.
"""

import logging
import time
from collections.abc import Awaitable, Callable
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field

from schemas.task_spec import TaskSpec

from .llm_runner import AsyncLLMRunner, ChatMessage, LLMConfig

logger = logging.getLogger("openeval.engine.react")

REACT_SYSTEM_PROMPT = """You are an autonomous AI evaluation agent for technical benchmarks.

You operate inside a sandboxed workspace and have access to the following tools:
1. `execute_bash`: Run terminal commands. Input: `command` (e.g. "pytest tests/").
2. `view_file`: Read contents of a file. Input: `path`.
3. `write_file`: Write content to a file. Input: `path` and `content`.
4. `finish`: Conclude work once verified. Input: `summary`.

### Instructions:
- In each turn, analyze state, explain reasoning in `thought`, and execute ONE action.
- You must always respond with a valid JSON object matching the required schema.
- Before calling `finish`, run tests to ensure your solution is complete.
"""


class AgentAction(BaseModel):
    """Structured action generated by the agent at each step."""

    model_config = ConfigDict(extra="ignore")

    thought: str = Field(..., description="Internal chain-of-thought reasoning and plan")
    tool: Literal["execute_bash", "view_file", "write_file", "finish"] = Field(
        ..., description="The chosen tool"
    )
    command: str | None = Field(default=None, description="Shell command for execute_bash")
    path: str | None = Field(default=None, description="Target file path for view/write")
    content: str | None = Field(default=None, description="File content for write_file")
    summary: str | None = Field(default=None, description="Final summary for finish")


class AgentStep(BaseModel):
    """Telemetry and trace for a single turn in the ReAct loop."""

    step_number: int
    thought: str
    action: AgentAction
    observation: str
    latency_ms: float = 0.0
    tokens_used: int = 0
    timestamp: float = Field(default_factory=time.time)


class AgentTrajectory(BaseModel):
    """Complete execution history and evaluation trace of an agent run."""

    task_id: str
    model: str
    steps: list[AgentStep] = Field(default_factory=list)
    total_steps: int = 0
    total_tokens: int = 0
    total_duration_sec: float = 0.0
    status: Literal["completed", "max_steps_exceeded", "timeout", "error"] = "completed"
    final_summary: str | None = None
    error_message: str | None = None


# Type alias for tool execution callbacks
ToolExecutor = Callable[[AgentAction], Awaitable[str]]


class ReActAgent:
    """Multi-step ReAct agent harness for autonomous evaluation tasks."""

    def __init__(
        self,
        runner: AsyncLLMRunner,
        executor: ToolExecutor,
    ) -> None:
        self.runner = runner
        self.executor = executor

    async def solve_task(
        self,
        task: TaskSpec,
        config: LLMConfig | None = None,
        on_step_callback: Callable[[AgentStep], Any] | None = None,
        on_step_start: Callable[[int], Any] | None = None,
    ) -> AgentTrajectory:
        """Execute the full ReAct problem-solving loop against a benchmark task.

        Args:
            task: Validated TaskSpec containing instruction prompt and limits.
            config: Optional LLM sampling config.
            on_step_callback: Optional hook triggered after each step (for live streaming).
            on_step_start: Optional hook triggered before each step.

        Returns:
            Complete AgentTrajectory recording every turn, tool output, and metric.
        """
        cfg = config or LLMConfig(
            temperature=task.agent.temperature,
            max_tokens=2048,
        )

        max_steps = task.agent.max_steps
        messages: list[ChatMessage] = [
            ChatMessage(role="system", content=REACT_SYSTEM_PROMPT),
            ChatMessage(
                role="user",
                content=(
                    f"## Evaluation Task: {task.task_id}\n\n"
                    f"### Instructions:\n{task.instruction_text}\n\n"
                    f"Please begin by investigating the workspace."
                ),
            ),
        ]

        trajectory = AgentTrajectory(
            task_id=task.task_id,
            model=cfg.model,
        )

        start_time = time.perf_counter()

        for step_idx in range(1, max_steps + 1):
            if on_step_start:
                on_step_start(step_idx)

            try:
                response = await self.runner.generate(
                    messages=messages,
                    config=cfg,
                    response_schema=AgentAction,
                )

                if response.parsed_json is None:
                    # Fallback if raw text couldn't be parsed
                    action = AgentAction(
                        thought=response.content,
                        tool="execute_bash",
                        command="echo 'No structured action parsed'",
                    )
                else:
                    action = AgentAction.model_validate(response.parsed_json)

                # Check for termination
                if action.tool == "finish":
                    step = AgentStep(
                        step_number=step_idx,
                        thought=action.thought,
                        action=action,
                        observation="Task marked as finished by agent.",
                        latency_ms=response.usage.latency_ms,
                        tokens_used=response.usage.total_tokens,
                    )
                    trajectory.steps.append(step)
                    trajectory.total_tokens += response.usage.total_tokens
                    trajectory.status = "completed"
                    trajectory.final_summary = action.summary or action.thought

                    if on_step_callback:
                        on_step_callback(step)
                    break

                # Execute tool
                observation = await self.executor(action)

                step = AgentStep(
                    step_number=step_idx,
                    thought=action.thought,
                    action=action,
                    observation=observation,
                    latency_ms=response.usage.latency_ms,
                    tokens_used=response.usage.total_tokens,
                )

                trajectory.steps.append(step)
                trajectory.total_tokens += response.usage.total_tokens

                if on_step_callback:
                    on_step_callback(step)

                # Feed thought + action + observation back into history
                messages.append(
                    ChatMessage(
                        role="assistant",
                        content=response.content,
                    )
                )
                messages.append(
                    ChatMessage(
                        role="user",
                        content=f"Observation for `{action.tool}`:\n```\n{observation}\n```",
                    )
                )

            except Exception as e:
                logger.error("Error in ReAct step %d: %s", step_idx, e)
                trajectory.status = "error"
                trajectory.error_message = str(e)
                break

        else:
            trajectory.status = "max_steps_exceeded"

        trajectory.total_steps = len(trajectory.steps)
        trajectory.total_duration_sec = round(time.perf_counter() - start_time, 2)
        return trajectory
