apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openeval-data-pvc
  labels:
    app: openeval-studio
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
