apiVersion: v1
kind: Service
metadata:
  name: openeval-service
  labels:
    app: openeval-studio
spec:
  type: ClusterIP
  selector:
    app: openeval-studio
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: Tcp
