#include "graph.h"

static const int B = 5;               // try 1..5 consecutive edge removals
static const int spurinterval = 3;    // sample every spurinterval nodes across path
static const int psblts_cap = 800;    // candidateidate psblts cap
static const int itr_nodes = 4; // after picking a candidateidate, we may generate local spurs

static inline uint64_t edge_key(int u, int v)
{
  return ((uint64_t)(uint32_t)u << 32) | (uint64_t)(uint32_t)v;
}

// hash function fully generated by chatgpt!

static inline uint64_t hash_path(const std::vector<int> &path)
{
  const uint64_t FNV_offset = 1469598103934665603ULL;
  const uint64_t FNV_prime = 1099511628211ULL;
  uint64_t h = FNV_offset;
  for (int x : path)
  {
    h ^= (uint64_t)x;
    h *= FNV_prime;
  }
  return h;
}

static inline std::unordered_set<uint64_t> path_edges(const std::vector<int> &path)
{
  std::unordered_set<uint64_t> s;
  if (path.size() < 2)
    return s;
  s.reserve(path.size() - 1);
  for (size_t i = 0; i + 1 < path.size(); i++)
    s.insert(edge_key(path[i], path[i + 1]));
  return s;
}

static inline double overlap_perc_set(const std::unordered_set<uint64_t> &A, const std::unordered_set<uint64_t> &B)
{
  if (A.empty() || B.empty())
    return 0.0;
  // find perc of the smaller path that is overslapping
  const std::unordered_set<uint64_t> *small = &A, *big = &B;
  if (A.size() > B.size())
  {
    small = &B;
    big = &A;
  }
  int common = 0;
  // iterating over smol so i iterate less
  for (auto &e : *small)
    if (big->count(e))
      common++;
  return 100.0 * (double)common / (double)small->size();
}

std::vector<std::vector<int>> Graph::k_short_heuristic(int src, int target, int k, int overlap_threshold)
{
  std::vector<std::vector<int>> ans;

  double shotty = 0.0;
  std::vector<int> base = shortest_path(src, target, shotty);
  if (base.empty())
    return ans;

  struct candidate
{
    std::vector<int> p;
    double len;
    double penalty;

    bool operator<(const candidate &other) const
    {
        if (penalty != other.penalty)
            return penalty < other.penalty;
        return len < other.len;
    }
};


  std::vector<candidate> selected;
  selected.reserve(k);
  selected.push_back({base, shotty});
  std::unordered_set<uint64_t> bpaths = path_edges(base);

  std::vector<candidate> psblts; // possibilities of candidates
  psblts.reserve(psblts_cap);
  std::unordered_set<uint64_t> psblts_seen;
  psblts_seen.insert(hash_path(base));

  std::vector<int> removed;

  int n = (int)base.size();
  for (int pos = 0; pos + 1 < n; pos += spurinterval)
  {
    for (int rem = 1; rem <= B && pos + rem < n; rem++)
    {
      removed.clear();
      // block rem consecutive edges at pos to pos+rem-1
      for (int j = 0; j < rem; j++)
      {
        int u = base[pos + j], v = base[pos + j + 1];
        bool found = false;
        for (auto &[v_id, eid] : nodes[u].adj)
        {
          if (v_id == v){
            edges[eid].blocked = true;
            removed.push_back(eid);
          }
        }
        // nothing to block for u,v
      }

      double newlen = 0.0;
      std::vector<int> np = shortest_path(src, target, newlen);

      // reestoree edges
      for (int eid : removed) edges[eid].blocked = false;


      if (np.empty())
        continue;

      uint64_t h = hash_path(np);
      if (psblts_seen.count(h))
        continue;

      // skip if equal to any selected
      // TODO : why not hash
      bool eq_selected = false;
      for (auto &s : selected)
        if (s.p == np)
        {
          eq_selected = true;
          break;
        }
      if (eq_selected)
        continue;

      std::unordered_set<uint64_t> np_set = path_edges(np);
      int overlp_cnt = 0;
      if (overlap_perc_set(bpaths, np_set) > overlap_threshold)
        overlp_cnt++;
      double dist_pen = (shotty > 0.0) ? ((newlen - shotty) / shotty + 0.1) : (newlen + 0.1);
      double penalty = overlp_cnt * dist_pen;

      psblts.emplace_back(candidate{np, newlen, penalty});
      psblts_seen.insert(h);

      if ((int)psblts.size() >= psblts_cap)
        break;
    }
    if ((int)psblts.size() >= psblts_cap)
      break;
  }

  // sort psblts by penalty then length
  std::sort(psblts.begin(), psblts.end());

  size_t idx = 0;
  // TODO :duplicate??
  while ((int)selected.size() < k && idx < psblts.size())
  {
    candidate cand = std::move(psblts[idx++]);
    bool dup = false;
    for (auto &s : selected)
      if (s.p == cand.p)
      {
        dup = true;
        break;
      }
    if (dup)
      continue;

    selected.push_back(cand);
    auto cand_set = path_edges(cand.p);

    // local spurs
    for (int r = 0; r < itr_nodes && (int)psblts.size() < psblts_cap; r++)
    {
      int m = (int)cand.p.size();
      if (m < 2)
        break;
      int step = std::max(1, m / 10);
      for (int pos = 0; pos + 1 < m; pos += step)
      {
        for (int rem = 1; rem <= 3 && pos + rem < m; rem++)
        {
          removed.clear();
          for (int j = 0; j < rem; j++)
          {
            int u = cand.p[pos + j], v = cand.p[pos + j + 1];
            for (auto &[v_id, eid] : nodes[u].adj)
            {
              if (v_id == v)
              {
                edges[eid].blocked = true;
                removed.push_back(eid);
              }
            }
          }

          double newlen = 0.0;
          auto np = this->shortest_path(src, target, newlen);

          for (int eid : removed) edges[eid].blocked = false;

          if (np.empty())
            continue;

          bool same = false;
          for (auto &s : selected)
            if (s.p == np)
            {
              same = true;
              break;
            }
          if (same)
            continue;

          uint64_t h = hash_path(np);
          if (psblts_seen.count(h))
            continue;

          auto np_set = path_edges(np);
          int overlp_cnt = 0;
          if (overlap_perc_set(cand_set, np_set) > overlap_threshold)
            overlp_cnt++;
          double dist_pen = (shotty > 0.0) ? ((newlen - shotty) / shotty + 0.1) : (newlen + 0.1);
          double penalty = overlp_cnt * dist_pen;

          psblts.emplace_back(candidate{np, newlen, penalty});
          psblts_seen.insert(h);

          if ((int)psblts.size() >= psblts_cap)
            break;
        }
        if ((int)psblts.size() >= psblts_cap)
          break;
      }
    }

    if (idx < psblts.size())
    {
      std::sort(psblts.begin() + idx, psblts.end(), [](const candidate &a, const candidate &b)
                {
                if (a.penalty == b.penalty) return a.len < b.len;
                return a.penalty < b.penalty; });
    }
  }

  // sort selected by length ascending (shortest path first)
  std::sort(selected.begin(), selected.end(), [](const candidate &a, const candidate &b)
            { return a.len < b.len; });

  ans.reserve(selected.size());
  for (auto &s : selected)
    ans.push_back(s.p);
  return ans;
}